### PR TITLE
Update to NSB 8

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Updates the package to NServiceBus 8

### CODE REVIEW

**Comment by jbogard** [comment]
Build failure :(

**Comment by SzymonPobiega** [comment]
Something seems to be broken also for the dependabot PRs. It seems to expect the output to be in `net472\artifacts\NServiceBus.MessageRouting.UnitTests.dll` but that's weird because the `build.ps1` assumes the `artifacts` is in the root of the repo.

Am I assuming correctly that the intention was to put the output into the `artifacts` folder in the root of the repo? This seems to be aligned with the build script and the gitignore. If that's the case I can try to figure out what broke the csproj output and try to fix it.

**Comment by jbogard** [comment]
lol 
image

**Comment by jbogard** [comment]
@SzymonPobiega I fixed this in `master` if you want to merge

**Comment by SzymonPobiega** [comment]
Thanks @jbogard . I rebased and force-pushed.

**Review by jbogard — APPROVED** [review]

**Pull request merged**
